<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Site
 *
 * @ORM\Table(name="site")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\SiteRepository")
 */
class Site
{
    // Adding personal methods / variables
    public function __toString()
    {
        // Return  the site object with  "[ICAO] - [NAME] - [CITY] format, when __toString is called.
        return $this->icao. " - " . $this->name. " - " . $this->city;
    }

    /*
     * Autogenerated methods / variables
     */

    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */

    private $arrival;
    /**
     * @ORM\OneToMany(targetEntity="AppBundle\Entity\Flight", mappedBy="arrival")
     */

    private $departures;
    /**
     * @ORM\OneToMany(targetEntity="AppBundle\Entity\Flight", mappedBy="departure")
     */

    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=128)
     */
    private $name;

    /**
     * @var string
     *
     * @ORM\Column(name="icao", type="string", length=4)
     */
    private $icao;

    /**
     * @var float
     *
     * @ORM\Column(name="latitude", type="float")
     */
    private $latitude;

    /**
     * @var float
     *
     * @ORM\Column(name="longitute", type="float")
     */
    private $longitute;

    /**
     * @var string
     *
     * @ORM\Column(name="city", type="string", length=128)
     */
    private $city;


    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     *
     * @return Site
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set icao
     *
     * @param string $icao
     *
     * @return Site
     */
    public function setIcao($icao)
    {
        $this->icao = $icao;

        return $this;
    }

    /**
     * Get icao
     *
     * @return string
     */
    public function getIcao()
    {
        return $this->icao;
    }

    /**
     * Set latitude
     *
     * @param float $latitude
     *
     * @return Site
     */
    public function setLatitude($latitude)
    {
        $this->latitude = $latitude;

        return $this;
    }

    /**
     * Get latitude
     *
     * @return float
     */
    public function getLatitude()
    {
        return $this->latitude;
    }

    /**
     * Set longitute
     *
     * @param float $longitute
     *
     * @return Site
     */
    public function setLongitute($longitute)
    {
        $this->longitute = $longitute;

        return $this;
    }

    /**
     * Get longitute
     *
     * @return float
     */
    public function getLongitute()
    {
        return $this->longitute;
    }

    /**
     * Set city
     *
     * @param string $city
     *
     * @return Site
     */
    public function setCity($city)
    {
        $this->city = $city;

        return $this;
    }

    /**
     * Get city
     *
     * @return string
     */
    public function getCity()
    {
        return $this->city;
    }
    /**
     * Constructor
     */
    public function __construct()
    {
        $this->id = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * Get departures
     *
     * @return integer
     */
    public function getDepartures()
    {
        return $this->departures;
    }

    /**
     * Add id
     *
     * @param \AppBundle\Entity\Flight $id
     *
     * @return Site
     */
    public function addId(\AppBundle\Entity\Flight $id)
    {
        $this->id[] = $id;

        return $this;
    }

    /**
     * Remove id
     *
     * @param \AppBundle\Entity\Flight $id
     */
    public function removeId(\AppBundle\Entity\Flight $id)
    {
        $this->id->removeElement($id);
    }

    /**
     * Get arrival
     *
     * @return integer
     */
    public function getArrival()
    {
        return $this->arrival;
    }

    /**
     * Add departure
     *
     * @param \AppBundle\Entity\Flight $departure
     *
     * @return Site
     */
    public function addDeparture(\AppBundle\Entity\Flight $departure)
    {
        $this->departures[] = $departure;

        return $this;
    }

    /**
     * Remove departure
     *
     * @param \AppBundle\Entity\Flight $departure
     */
    public function removeDeparture(\AppBundle\Entity\Flight $departure)
    {
        $this->departures->removeElement($departure);
    }
}
